version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    # CI에서 빌드된 이미지를 pull 해 사용
    image: YOUR_DOCKER_USERNAME/auth-service-backend:${IMAGE_TAG}
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development

  frontend:
    # CI에서 빌드된 이미지를 pull 해 사용
    image: YOUR_DOCKER_USERNAME/auth-service-frontend:${IMAGE_TAG}
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo-data:
