version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    image: "${DOCKER_USERNAME}/auth-service-backend:${IMAGE_TAG}"
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development
    depends_on:
      - mongo

  frontend:
    image: "${DOCKER_USERNAME}/auth-service-frontend:${IMAGE_TAG}"
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
