name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Load SSH key into ssh-agent
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 4. Build and push Docker image
      - name: Build and push Docker image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.sha }}

      # 5. Deploy to EC2 via deploy.sh (경로 수정)
      - name: Deploy to EC2 instance via SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -s' \
            < ./deploy.sh
