name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) SSH key for deploy.sh
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) Docker Hub login
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" \
          | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 4) Build & push backend
      - name: Build and push backend image
        working-directory: backend
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:latest

      # 5) Build & push frontend
      - name: Build and push frontend image
        working-directory: frontend
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:latest

      # 6) Deploy via deploy.sh
      - name: Deploy to EC2 via deploy.sh
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -s' \
            < ./deploy.sh
