name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1) Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Load SSH key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 4) Build & push backend image
      - name: Build and push backend image
        working-directory: backend
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-backend:latest

      # 5) Build & push frontend image
      - name: Build and push frontend image
        working-directory: frontend
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-frontend:latest

      # 6) Add EC2 host to known_hosts
      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # 7) SSH connection test (fast-fail)
      - name: SSH 접속 테스트
        run: |
          ssh -vvv \
            -o ConnectTimeout=5 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            exit

      # 8) Deploy to EC2 via deploy.sh
      - name: Deploy to EC2 via deploy.sh
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=10 \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'bash -s' < ./deploy.sh
